# rw=读写分离, vertical=垂直分库, horizontal=水平分库分表
spring.datasource.dynamic.datasource.mysql.driver-class-name=org.apache.shardingsphere.driver.ShardingSphereDriver
spring.datasource.dynamic.datasource.mysql.url=jdbc:shardingsphere:classpath:yml/shardingsphere-${sharding.mode:rw}.yml